[package]
name = "zb_io"
version.workspace = true
edition = "2024"
rust-version.workspace = true

[dependencies]
flate2.workspace = true
futures.workspace = true
libc.workspace = true
memchr.workspace = true
futures-util.workspace = true
rayon.workspace = true
regex.workspace = true
rustls.workspace = true
rustls-native-certs.workspace = true
webpki-roots.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tar.workspace = true
tokio.workspace = true
fs4.workspace = true
walkdir.workspace = true
xz2.workspace = true
zstd.workspace = true
zip.workspace = true
tracing.workspace = true
strsim.workspace = true
tempfile.workspace = true
zb_core = { path = "../zb_core" }
arwen = "0.0.5"
object = "0.39.1"

[features]
android-support = ["reqwest/native-tls"]

[target.'cfg(not(target_os = "android"))'.dependencies]
reqwest = { workspace = true }

[target.'cfg(target_os = "android")'.dependencies]
reqwest = { version = "0.13.1", default-features = false, features = ["json", "stream", "http2"] }

[dev-dependencies]
tempfile.workspace = true
wiremock.workspace = true
